### ISSUE TITLE
bsr out of range not reported by assembler or linker

### ISSUE THREAD

**Issue by skeetor** [bebbo/binutils-gdb#10]
I have a repo at https://github.com/skeetor/amiga-utils. In the file https://github.com/skeetor/amiga-utils/blob/master/utilslib/AmigaUtils/src/SystemTakeover.s there is the line "jsr	WaitRaster". Oriignaly this was a "bsr	WaitRaster". I when I compile and link that the symbol "WaitRaster" is accepted without any error, but when I run the binary, it crashes, because the "bsr" instruction points to some invalid address. It looks as if the function "WaitRaster" which is in a separate module, may be out of range, but in this case I would expect an error from the linker. Replacing that with "jsr" instead, fixes the problem.

A discussion can be found here: http://eab.abime.net/showthread.php?p=1366266#post1366266

**Comment by bebbo** [comment]
please test

**Comment by skeetor** [comment]
What do I need to update for this? Recomplie my amigaos suite?

**Comment by bebbo** [comment]
```
make update -j
make binutils -j6
```
should be sufficient, since there should be no code using pcrel jumps to other object files. (no warrants)

**Comment by skeetor** [comment]
Looks good now! :D I now get a relocation error now when I try to use "bsr.s" and when I just use "bsr" it's pointing now to the correct address.

Cool! Thanks!
