### ISSUE TITLE
Debugger runs into assertion while debugging ScummVM

### ISSUE THREAD

**Issue by mheyer32** [bebbo/binutils-gdb#12]
As soon as the first breakpoint is hit, I'm running into this assertion and the debugger will quit the debugee:

`>~"/home/matze/amigatoolchain/amiga-gcc/projects/binutils/gdb/gdbtypes.c:1765: internal-error: int internal_type_vptr_fieldno(type*): Assertion `TYPE_CODE (type) == TYPE_CODE_STRUCT || TYPE_CODE (type) == TYPE_CODE_UNION' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable.\nQuit this debugging session? "`

**Comment by mheyer32** [comment]
>~"/home/matze/amigatoolchain/amiga-gcc/projects/binutils/gdb/gnu-v3-abi.c:209: internal-error: int gnuv3_dynamic_class(type*): Assertion `TYPE_CODE (type) == TYPE_CODE_STRUCT || TYPE_CODE (type) == TYPE_CODE_UNION' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable.\nCreate a core file of GDB? "
>~"(y or n) [answered Y; input not from terminal]\n"

**Comment by bebbo** [comment]
binutils is currently an open construction site...
... you could try to build gdb from binutils-gdb 2d5c5290ca131b44b79cb8c36c19cddc20ba4752

**Comment by mheyer32** [comment]
I had time testing this today.
2d5c529  did not work for me. It produced a corrupted executable that will crash in illegal instructions.

**Comment by mheyer32** [comment]
![YoDawg](https://user-images.githubusercontent.com/33539855/80270980-9f48db80-8671-11ea-973e-451b78179f52.jpg)
SCNR :-)

**Comment by bebbo** [comment]
is this still valid?
