### ISSUE TITLE
"--gc-section" ignores "--undefined"

### ISSUE THREAD

**Issue by githubaf** [bebbo/binutils-gdb#25]
"--gc-section" works nicely now and removes all unused stuff.

Sometimes an unused variable should stay in the executable, even if it is not directly used. Examples are the Amiga Version-String $VER or the new $STACK: Token. 

There is a linker option to tell the linker, which unused variable or function should be kept. That works in linux gcc but does not work in your Amiga gcc.

Please find an example attached

[used_test.zip](https://github.com/bebbo/binutils-gdb/files/9018973/used_test.zip)

**Comment by bebbo** [comment]
hm, you know that there are preceding underscores on the Amiga?

**Comment by githubaf** [comment]
You are right! With underscores it works.
But I have have to be pointed directly to such obvious solutions ;-)

OK, then it's fine and I have no more complaints here.
