### ISSUE TITLE
PC relative with 32-bit absolute offset calculated wrongly

### ISSUE THREAD

**Issue by michalsc** [bebbo/binutils-gdb#26]
Hello. When compiling PCrel code I have noticed that gcc is generating wrong offsets in the PC-relative addressing mode with 32-bit offset. Please see the example:

1. File test.s, using pc-relative call to an external function
```
	.text
	jsr (test_func, pc)
	rts
```
2. File call.s, the external function protected with "illegal" opcode
```
	.text
	.globl test_func
	illegal
test_func:
	rts
```
3. Compile both, and link them
```
> m68k-amigaos-gcc -c -m68040 test.s
> m68k-amigaos-gcc -c -m68040 call.s
> m68k-amigaos-gcc -m68040 -o test -ffreestanding -nostdlib test.o call.o
```
4. Check disassembly output or run in m68k simulator (68020+ required)
```
> m68k-amigaos-objdump -S test

test:     file format amiga


Disassembly of section .text:

00000000 00000000 __stext:
   0:	4ebb 0170 0000 	jsr (c c __stext+0xc,pc)
   6:	000a 
   8:	4e75           	rts
   a:	0000 4afc      	ori.b #-4,d0

0000000e 0000000e test_func:
   e:	4e75           	rts

```

as you may see the jar is doing pc-relative jump to address $0c, which is the illegall opcode, although it should have jumped to address $0e. I think the problem is caused by ignoring the first extension word ($0170) in the opcode when the pc-relative offsets are calculated.

**Comment by bebbo** [comment]
That issue isn't that easy as it looks. pc relative jumps to other files, sections and so on are handled different between elf and amiga hunk. 

Why should the value `6:	0002` of the caller file `test.o` contribute to the offset calculation?

**Comment by michalsc** [comment]
> That issue isn't that easy as it looks. pc relative jumps to other files, sections and so on are handled different between elf and amiga hunk.
> 
> Why should the value `6: 0002` of the caller file `test.o` contribute to the offset calculation?

I have already noticed it. Still, as mentioned in another comment, it turned out to be related to the ``off`` calculation in bfd/amigoslink.c of binutils. In case of 16-bit reloc (H_PC16) the computed ``off`` value equals 0. In case of H_PC32, the computed ``off`` equals 2 and causes the relocation to be wrong.

This is how it looks like if I modify the example from initial report to following:

```
	.text
	jsr (test_func, pc)
	jsr (test_func:w, pc)
	bsr.w test_func
	bsr.l test_func
	rts
```

with binutils **after** the commit I've pointed to, disassembly from linked file will be:

```
00000000 00000000 __stext:
   0:	4ebb 0170 0000 	jsr (18 18 __stext+0x18,pc)
   6:	0016 
   8:	4eba 0010      	jsr 1a 1a test_func(pc)
   c:	6100 000c      	bsr.w 1a 1a test_func
  10:	61ff 0000 0008 	bsr.l 1a 1a test_func
  16:	4e75           	rts
  18:	4afc           	illega.l

0000001a 0000001a test_func:
```

by forcing ``off`` to 0 (as it was prior to the aforementioned commit), I get following, correct, disassembly:

```
00000000 00000000 __stext:
   0:	4ebb 0170 0000 	jsr (1a 1a test_func,pc)
   6:	0018 
   8:	4eba 0010      	jsr 1a 1a test_func(pc)
   c:	6100 000c      	bsr.w 1a 1a test_func
  10:	61ff 0000 0008 	bsr.l 1a 1a test_func
  16:	4e75           	rts
  18:	4afc           	illega.l

0000001a 0000001a test_func:
  1a:	4e75           	rts
```

The problem here is, the PC taken by the PC indirect with index mode is relative to the extension word (0x0170, second word of the JSR instruction) and not relative to the offset itself. Therefore, off = 2 is, in this very case, incorrect.

**Comment by bebbo** [comment]
The problem starts in the assembler `gas` and the last attempts to resolve it were bogus.
This is a new attempt...
... please test (in 42 mins from now^^)

**Comment by bebbo** [comment]
bump

**Comment by michalsc** [comment]
It is working good now, even if for some reason the newly updated lib nix fails to build :) I'm closing the issue now.

**Comment by bebbo** [comment]
> It is working good now, even if for some reason the newly updated lib nix fails to build :) I'm closing the issue now.

it passes the configured tests... maybe you need a full clean build

**Comment by michalsc** [comment]
Will do, right now it fails with
```
➜  amiga-gcc git:(master) gmake all SHELL=/usr/local/bin/bash    
make libnix...
make libnix...failed
 #define __NO_INLINE__
 
<built-in>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
/Users/michal/git/amiga-gcc/projects/libnix/sources/nix/stdio/ferror.c:1:0: error: "__NO_INLINE__" redefined [-Werror]
 #define __NO_INLINE__```

**Comment by michalsc** [comment]
I cannot tell, I use clean tree cloned from your GitHub and no personal changes to it now. Btw, here you can see the full log from libnix build: https://pastebin.com/feKQM0ZW

**Comment by bebbo** [comment]
your CFLAGS in libnix are empty...

a) CFLAGS_FOR_TARGET is defined and empty
b) your make is not compatible and doesn't handle `CFLAGS_FOR_TARGET ?= -O2 -fomit-frame-pointer`

try `export CFLAGS_FOR_TARGET="-O2 -fomit-frame-pointer"` in your shell
