### ISSUE TITLE
SUBALIGN does not Appear to Work

### ISSUE THREAD

**Issue by RetroRevivalGames** [bebbo/binutils-gdb#30]
Hi Bebbo. Since #29 I've gotten a ROM image for the SEGA Mega Drive to build and run successfully. 

I've come across one more minor issue. I'm using -ffunction-sections and -fdata-sections along with --gc-sections to reduce ROM size. It works nicely but the linker seems to force a 4-byte alignment between each input section. In other words, each function/variable now has a few 0 bytes to align the next function/variable on a 4-byte boundary, which can chew up some space for larger programs. I'm trying to align on a 2-byte boundary.

Same lds. I've tried different values for the .text section's SUBALIGN command (0, 1, 2, 3, 4) and each time it aligns on a 4-byte boundary.
```
ENTRY(__START)

MEMORY
{
	rom (rx)  : ORIGIN = 0x00000000, LENGTH = 0x00400000
	ram (rwx) : ORIGIN = 0x00FF0000, LENGTH = 0x00010000
}

SECTIONS
{
	.text 0x00000000 : SUBALIGN(2) {
		KEEP(*(.header))
		*(.boot)
		*(.main)
		*(.text*)
		*(.vdp)
		*(.rodata .rodata.*)
	} > rom
	__stext = SIZEOF(.text);

	.data 0x00FF0000 : AT( ADDR(.text) + SIZEOF(.text) ) {
		*(.data*)
		*(.asmdata)
		FILL(0x00)
		. = ALIGN(2);
	} > ram
	__sdata = SIZEOF(.data);

	.bss 0x00FF0000 + SIZEOF(.data) : {
		*(.bss) 
	} > ram
}
```
![image](https://user-images.githubusercontent.com/87720313/210686312-990ddbc7-6e91-4add-ba8a-d17f6d8bd79c.png)

Not sure how much it would take to remedy this but if it's not too much of a hassle it'd be awesome if this was implemented.

I've done a little research into it. Looks like `asection` struct has align_power variable. Not sure if that could be used to allow users to configure the input section alignments via SUBALIGN?

**Comment by bebbo** [comment]
the assembler already alignes everything at 4 byte boundaries:
```
START:
  rts
```
->
```
00000000 00000000 START:
   0:   4e75            rts
   2:   0000    .short 0x0000
```

**Comment by bebbo** [comment]
and it's hard coded atm:
```
newsect->alignment_power = 2;
```

**Comment by bebbo** [comment]
And last but not least: the Amiga hunk file format supports only multiples of 4.
=> this won't work using Amiga hunks.

workarounds:
- use a different target 
- use function/data sections only to figure what gets used, then attribute (with conditional defines) these with special named sections. All wanted stuff ends up in these named sections.

**Comment by RetroRevivalGames** [comment]
Makes sense. I figured hunk would have that alignment limitation.

As far as using a different target, this toolchain only supports hunk correct? I remember trying to compile amiga-gcc with `TARGET=m68k-elf` and it failed.

**Comment by bebbo** [comment]
> Makes sense. I figured hunk would have that alignment limitation.
> 
> As far as using a different target, this toolchain only supports hunk correct? I remember trying to compile amiga-gcc with `TARGET=m68k-elf` and it failed.

a) why aren't you using a stock m68k-elf?
b) `make TARGET=m68k-elf gcc` should work, but other stuff fails...

**Comment by RetroRevivalGames** [comment]
> a) why aren't you using a stock m68k-elf?

Stack heavy / slower assembly generated

> b) make TARGET=m68k-elf gcc should work, but other stuff fails...

Unfortunately this is failing at binutils gas.

![image](https://user-images.githubusercontent.com/87720313/210805591-17048521-9f44-4fd5-bfdd-347fcf9a7bc2.png)

**Comment by bebbo** [comment]
make binutils -j30 TARGET=m68k-elf
make binutils bfd...
make binutils bfd...done
make binutils gas...
make binutils gas...done
make binutils binutils...
make binutils binutils...done
make binutils ld...
make binutils ld...done
install binutils...
install binutils...done

**Comment by RetroRevivalGames** [comment]
OK. Building only binutils does work. I was building all of gcc using `make gcc TARGET=m68k-elf`

**Comment by bebbo** [comment]
gcc should compile too, but not newlib

**Comment by RetroRevivalGames** [comment]
Tried it again. Yes, looks like it built correctly. Tried it out and it works perfectly. Exactly what I was looking for, the high efficiency of your assembly generation with the elf binary format. I even got lto plugins to work with small modifications to the Makefile in amiga-gcc. Just remove `--disable-plugins` from binutils configuration.

Thank you Bebbo.

**Comment by bebbo** [comment]
> Tried it again. Yes, looks like it built correctly. Tried it out and it works perfectly. Exactly what I was looking for, the high efficiency of your assembly generation with the elf binary format. I even got lto plugins to work with small modifications to the Makefile in amiga-gcc. Just remove `--disable-plugins` from binutils configuration.
> 
> Thank you Bebbo.

I will omit `--disable-plugins` if target is `m68k-elf`.
