### ISSUE TITLE
CreatePort crashes

### ISSUE THREAD

**Issue by alexalkis** [bebbo/binutils-gdb#31]
```
#include <clib/alib_protos.h>
#include <proto/dos.h>
#include <stdio.h>

int main(int argc, char const *argv[]) {
  struct MsgPort *port;

  port = CreatePort(NULL, 0);
  if (port) {
    PutStr("Port opened ok, closing now...\n");
    DeletePort(port);
  }
  return 0;
}

```
Compile with: m68k-amigaos-gcc -s -noixemul -Os -o testcp testcp.c
This crashes.  I've narrowed down (from a big program) to CreatePort and this is a minimal source code.

The above does not crash with SAS/C.

**Comment by bebbo** [comment]
something broke during upgrade to 2.38
the branch `amiga-2.35.2` is ok

**Comment by bebbo** [comment]
update the repo and use `make branch mod=... branch=...`
```
git pull
make branch mod=binutils branch=amiga-2.35.2
```
It is already working but refreshes all modules... the change should be live soon,
or use this:
```
pushd projects/binutils
git fetch origin amiga-2.35.2:amiga-2.35.2
git checkout amiga-2.35.2
git branch --set-upstream-to=origin/amiga-2.35.2 amiga-2.35.2
popd
```
plus update the .repos file manually.

**Comment by bebbo** [comment]
DANG! I found the cause: the binutils switched the sizes from `size=2**x` to x, thus 0->1, 1->2, 2->4. So I have to apply this to the Amiga code ...

**Comment by bebbo** [comment]
The main branch `amiga` with binutils 2.39.0 is working again.
Please test.
You can switch back applying:
```
make branch mod=binutils branch=amiga
```

**Comment by alexalkis** [comment]
yeap. everything seems to work. thanks.

i/o seems to be _very_ slow with libnix.  Also, -m68020 bombs a project.  I'll try to make a test case and open a new issue or two.
