### ISSUE TITLE
gdb: Excess command line arguments ignored. (remote ...) macos (gdb v13.0.50) bgdbserver 

### ISSUE THREAD

**Issue by BastianZuehlke** [bebbo/binutils-gdb#36]
TCP/IP connection between both Amiga and Mac is working with several services.

a.out standard hello world c programm compiled with -g
on amiga: 
> bgdbserver a.out 
bgdbserver 1.3 (c) by Stefan 'Bebbo' Franke 2018-2019
loaded program a.out -> 0x75432b
hunk at: 0x1d50cac sz=0000333c
hunk at: 0x18ee014 sz=00000108
hunk at: 0x18ee124 sz=00000068
Running GDB server on port 2345

on mac:
>  /opt/amiga/bin/m68k-amigaos-gdb a.out target remote 192.168.188.154:2345 

Excess command line arguments ignored. (remote ...)
GNU gdb (GDB) 13.0.50.230920-120626-git
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-apple-darwin22.6.0 --target=m68k-amigaos".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...
/Users/bastianzuhlke/Development/target: No such file or directory.
(gdb) 

(gdb) run
Don´t know how to run. Try "help target".
(gdb)

--------

I am wondering about:
Excess command line arguments ignored. (remote ...)
/Users/bastianzuhlke/Development/target

**Comment by bebbo** [comment]
Guess you aren't using it correctly.
Please ask in a gdb support forum or have a look at one of the many examples, e.g. https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gnat_ugn_unw/Remote-Debugging-using-gdbserver.html

**Comment by BastianZuehlke** [comment]
Your guess is right. Thanks for the hint.
