### ISSUE TITLE
strip damages .o and .a files instead of stripping

### ISSUE THREAD

**Issue by githubaf** [bebbo/binutils-gdb#9]
I compiled libnix.a with -g and tried to strip it afterwards,
Stripping does not chage the size. (remains huge)
"stripped" libnix.a cannot be linked afterwards.

The same is true for .o files.
I created a simple hello_world.c and compiled it with -c -g
Then I stripped the hello.o file. It remains big.
Linking the "stripped" hello.o failed with "missing main".

Stripping executables works.

**Comment by bebbo** [comment]
no idea if this should succeed...

**Comment by githubaf** [comment]
Seems I did not really understand what strip is stripping depending on the commandline options...
Issue can probably be closed again.
